### PR TITLE
Upgrades helm client to 2.6.0

### PR DESCRIPTION
**Pull request by JosephSalisbury**
Towards https://github.com/giantswarm/giantswarm/issues/1600

### CODE REVIEW

**Comment by MarcelMue** [comment]
I am uncertain what exactly needs to be changed, I updated the versions of both helm and the plugin.

**Comment by JosephSalisbury** [comment]
I would recommend starting a local kubernetes cluster (minikube works), installing tiller there, and seeing if the integration works.

Both for 2.5.0 and 2.6.0

**Comment by JosephSalisbury** [comment]
@r7vme you used this version for archon?

**Comment by r7vme** [comment]
@JosephSalisbury i mean i've used same helm and plugin versions to deploy draughtsman :trollface: 

Not the Draughtsman itself.

**Comment by MarcelMue** [comment]
I have had some pretty strange problems with Helm + registry/Tiller/Draughtsman when testing this out locally. I would like to get this straight before we merge this. Especially since Helm 2.6.0 seems to have problems with Tiller 2.5.0 and a merge here means that we would have to upgrade Tiller on all our clusters manually with `helm init --upgrade`.

Any opinions?

**Comment by r7vme** [comment]
> pretty strange problems 
can you please describe litte bit?

> upgrade Tiller on all our clusters manually
I can help with this, imo we can merge new draugtsman and manually:
1) upgrade Tiller
2) upgrade Drauhtsman

So it won't break things automatically anyway

**Comment by MarcelMue** [comment]
Some problems: `helm init` reporting that it succeeded but the tiller deployment did not get satisfied (at all). Tiller running but draughtsman has problems installing charts. 

I would just like to make certain why it happens and then we can try the steps you suggested. I hope it won't take much longer.

**Comment by r7vme** [comment]
ping @JosephSalisbury and @MarcelMue 

I've updated Tiller to 2.6.2 https://github.com/giantswarm/giantswarm/issues/1600

and bumped clent version to 2.6.2 here. Please approve if OK.

**Comment by MarcelMue** [comment]
Okay from my side

**Comment by JosephSalisbury** [comment]
I can't approve, because it's my PR. Would recommend rolling out slowly, I could see there being edge cases, but this is the right way forward.

**Pull request merged**
