### PR TITLE
Delete tiller resources from kube-system namespace

### PR DESCRIPTION
**Pull request by tomahawk28**

### CODE REVIEW

**Comment by tomahawk28** [comment]
Tested `ginger`

```
D 02/18 09:46:38 creating in-cluster REST config | k8sclient/k8srestconfig/k8s_rest_config.go:148
D 02/18 09:46:38 created in-cluster REST config | k8sclient/k8srestconfig/k8s_rest_config.go:155
D 02/18 09:46:38 checking connection to Kubernetes | draughtsman/service/configurer/configmap/configmap.go:69
D 02/18 09:46:39 checking connection to Kubernetes | draughtsman/service/configurer/secret/secret.go:69
D 02/18 09:46:39 logging into registry | draughtsman/service/installer/helm/helm.go:268 | registry=quay.io | username=giantswarm+ginger
D 02/18 09:46:39 running helm command | draughtsman/service/installer/helm/helm.go:185 | name=login
D 02/18 09:46:47 ran helm command | draughtsman/service/installer/helm/helm.go:197 | name=login | stderr= | stdout= >>> Login succeeded

D 02/18 09:46:47 fetching metrics | draughtsman/service/installer/helm/helm.go:219
D 02/18 09:46:47 checking connection to Slack | draughtsman/service/notifier/slack/slack.go:86
D 02/18 09:46:48 checking remaining helm2 releases from draughtsman | draughtsman/service/helmmigration/migration.go:73
D 02/18 09:46:48 running server at http://0.0.0.0:8000 | microkit/server/server.go:308
D 02/18 09:46:49 no helm2 releases from draughtsman | draughtsman/service/helmmigration/migration.go:80
D 02/18 09:46:49 deleting service account `tiller` in namespace `kube-system` | draughtsman/service/helmmigration/migration.go:153
D 02/18 09:46:49 deleted service account `tiller` in namespace `kube-system` | draughtsman/service/helmmigration/migration.go:160
D 02/18 09:46:49 deleting service account `tiller-giantswarm` in namespace `kube-system` | draughtsman/service/helmmigration/migration.go:153
D 02/18 09:46:49 deleted service account `tiller-giantswarm` in namespace `kube-system` | draughtsman/service/helmmigration/migration.go:160
D 02/18 09:46:49 deleting cluster role binding `tiller` | draughtsman/service/helmmigration/migration.go:165
D 02/18 09:46:49 deleted cluster role binding `tiller` | draughtsman/service/helmmigration/migration.go:172
D 02/18 09:46:49 deleting cluster role binding `tiller-giantswarm-psp` | draughtsman/service/helmmigration/migration.go:165
D 02/18 09:46:49 deleted cluster role binding `tiller-giantswarm-psp` | draughtsman/service/helmmigration/migration.go:172
D 02/18 09:46:49 deleting cluster role binding `tiller-kube-system` | draughtsman/service/helmmigration/migration.go:165
D 02/18 09:46:49 deleted cluster role binding `tiller-kube-system` | draughtsman/service/helmmigration/migration.go:172
D 02/18 09:46:49 deleting pod security policy `tiller-giantswarm-psp` | draughtsman/service/helmmigration/migration.go:176
D 02/18 09:46:49 deleted pod security policy `tiller-giantswarm-psp` | draughtsman/service/helmmigration/migration.go:184
D 02/18 09:46:49 deleting network policy `tiller-giantswarm` in namespace `kube-system` | draughtsman/service/helmmigration/migration.go:187
D 02/18 09:46:49 deleted network policy `tiller-giantswarm` in namespace `kube-system` | draughtsman/service/helmmigration/migration.go:195
D 02/18 09:46:49 deleting deployment `tiller-deploy` in namespace `kube-system` | draughtsman/service/helmmigration/migration.go:197
D 02/18 09:46:49 deleted deployment `tiller-deploy` in namespace `kube-system` | draughtsman/service/helmmigration/migration.go:204
D 02/18 09:46:49 deleting 146 helm v2 backup configmaps | draughtsman/service/helmmigration/migration.go:219
D 02/18 09:46:50 deleted 146 helm v2 backup configmaps | draughtsman/service/helmmigration/migration.go:226
D 02/18 09:46:50 starting deployer | draughtsman/service/deployer/deployer.go:160
D 02/18 09:46:50 starting polling for github deployment events | draughtsman/service/eventer/github/github.go:105 | interval=1m0s
D 02/18 09:46:50 Fetching deployment events | draughtsman/service/eventer/github/github.go:114 | projectlist=[draughtsman aws-app-collection aws-operator cluster-operator]
D 02/18 09:46:53 fetched metrics | draughtsman/service/installer/helm/helm.go:221
```

**Review by rossf7 — APPROVED** [review]
LGTM

But there are also some rogue helm 2 releases in a few MCs. zeroed-crocodile on gollum is my favorite name.

**Review by kopiczko — APPROVED** [review]

**Comment by tomahawk28** [comment]
Wow, there are a lot of helm2 releases made by hand. 
```
helm2 ls
NAME                    REVISION        UPDATED                         STATUS          CHART                                                           APP VERSION     NAMESPACE
azure-cluster           1               Thu Nov 30 13:00:46 2017        DEPLOYED        azure-resource-lab-chart-0.1.0                                                  default
azure-operator          3               Thu Apr 16 11:33:58 2020        DEPLOYED        azure-operator-chart-1.0.0-30a03a91a78fe72c822a89d891a462...                    draughtsman
cert-resource-lab       1               Thu Nov 30 12:41:00 2017        DEPLOYED        cert-resource-lab-chart-0.1.0                                                   default
cert-resource-lab2      1               Fri Dec  1 23:30:18 2017        DEPLOYED        cert-resource-lab-chart-0.1.0                                                   default
cert-resource-lab3      1               Fri Dec  1 23:54:58 2017        DEPLOYED        cert-resource-lab-chart-0.1.0                                                   default
cluster-operator        2               Wed Jul 15 17:22:50 2020        DEPLOYED        cluster-operator-chart-1.0.0-e9ad862925855303e0db2652a5c7...                    draughtsman
credentiald             49              Thu May 21 12:37:22 2020        DEPLOYED        credentiald-chart-1.0.0-483d568554b5723c535223911e640f358...                    draughtsman
draughtsman-eventer     2               Mon Nov 20 15:45:41 2017        DEPLOYED        draughtsman-eventer-chart-1.0.0-fd040324c12b324e801e72a6e...                    draughtsman
elasticsearch           1               Tue Jan 29 16:10:40 2019        DEPLOYED        reporting-chart-1.0.0-[[ .SHA ]]                                                reporting
g8s-fluentbit           2               Fri Mar 16 11:44:04 2018        DEPLOYED        g8s-efk-chart-1.0.0-[[ .SHA ]]                                                  monitoring
processor               1               Wed Jan 30 11:51:10 2019        DEPLOYED        reporting-chart-1.0.0-[[ .SHA ]]                                                reporting
querying                1               Wed Jan 30 11:50:51 2019        DEPLOYED        reporting-querying-chart-1.0.0-[[ .SHA ]]                                       reporting
testbot                 3               Mon Dec 11 18:15:58 2017        DEPLOYED        testbot-chart-1.0.0-f54527079e7b09d4157814d72ce736b462d40b76                    draughtsman
zeroed-crocodile        1               Tue Nov 28 14:04:18 2017        DEPLOYED        azure-resource-lab-chart-0.1.0                                                  default
```

Does it make sense to delete all of them before we delete tiller?

**Comment by rossf7** [comment]
They look old except for azure-operator and cluster-operator which are the thiccc version. Not sure if they are still used? I would check with celestial.

I think we should delete them to clean up but maybe post in slack? So everyone is aware and to be sure they are not needed.

**Comment by tomahawk28** [comment]
Deleted all dangling helm2 releases. I'm going to merge this.

**Pull request merged**
