### PR TITLE
vendor update; helmclient

### PR DESCRIPTION
**Pull request by tomahawk28**
Vendor update; helmclient

### CODE REVIEW

**Review by rossf7 — CHANGES_REQUESTED** [review]
Same thing. Last time this broke and there were lots of alerts.

Let's discuss in the morning when we roll this out.

**Comment by rossf7** [comment]
Taking over here as @tomahawk28 is AFK tomorrow.

**Comment by tomahawk28** [comment]
Tested on `ginger`, it restores the original tiller version as v2.12.0. cc> @rossf7

**Review by rossf7 — APPROVED** [review]
LGTM

**Pull request merged**
